[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "netket-checkpoint"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Filippo Vicentini", email = "filippovicentini@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "netket>=3.12",
    "netket_pro",
]
